# Generated by Django 3.0.4 on 2020-08-06 04:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filesId', models.CharField(default='2ff1b28b8d0e9700f4d5b636aa93773d', max_length=32)),
                ('filesName', models.CharField(max_length=50, verbose_name='Nombre del Catálogo')),
                ('filesType', models.CharField(choices=[('Entidades', 'Entidades'), ('Municipios', 'Municipios'), ('Localidades', 'Localidades')], max_length=15, verbose_name='Tipo de Catálogo')),
                ('filesVersion', models.DateField(verbose_name='Versión')),
                ('uploadedDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(max_length=80)),
                ('statusDesc', models.CharField(max_length=254)),
                ('processStep', models.CharField(max_length=80)),
                ('task_id', models.CharField(default='NA', max_length=36)),
                ('buttons', models.CharField(default='', max_length=20, verbose_name='Botones Activos')),
                ('nextStep', models.CharField(default='', max_length=80, verbose_name='En Proceso')),
                ('catLoad', models.FileField(upload_to='catalogos/2ff1b28b8d0e9700f4d5b636aa93773d/', verbose_name='Catalogo')),
                ('eqvLoad', models.FileField(upload_to='catalogos/2ff1b28b8d0e9700f4d5b636aa93773d/', verbose_name='Tabla de Equivalencias')),
                ('actLoad', models.FileField(upload_to='catalogos/2ff1b28b8d0e9700f4d5b636aa93773d/', verbose_name='Registro de Actualización')),
                ('catTable', models.CharField(default='-', max_length=80, verbose_name='Temporal del Catálogo')),
                ('eqvTable', models.CharField(default='-', max_length=80, verbose_name='Temporal de la Tabla de Equivalencia')),
                ('actTable', models.CharField(default='-', max_length=80, verbose_name='Temporal del Registro de Actualización')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Catalogo cargado',
                'verbose_name_plural': 'Cargas de catálogos',
            },
        ),
        migrations.CreateModel(
            name='UploadFilesTrack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stepNumber', models.DecimalField(decimal_places=1, max_digits=3)),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(max_length=80)),
                ('statusDesc', models.CharField(max_length=254)),
                ('processStep', models.CharField(max_length=80)),
                ('task_id', models.CharField(default='NA', max_length=36)),
                ('buttons', models.CharField(default='', max_length=20, verbose_name='Botones Activos')),
                ('nextStep', models.CharField(default='', max_length=80, verbose_name='En Proceso')),
                ('UploadFiles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admincatalogos.UploadFiles')),
            ],
        ),
        migrations.CreateModel(
            name='MovTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filesType', models.CharField(choices=[('Entidades', 'Entidades'), ('Municipios', 'Municipios'), ('Localidades', 'Localidades')], max_length=15, verbose_name='Tipo de Catálogo')),
                ('cgo_act', models.CharField(max_length=2, verbose_name='Código de actualización')),
                ('descgo_act', models.CharField(max_length=110, verbose_name='Descripción del código de actualización')),
                ('move_type', models.CharField(choices=[('Alta', 'Alta'), ('Baja', 'Baja'), ('Ambas', 'Ambas')], default='Ambas', max_length=5, verbose_name='Tipo de movimiento (Alta/Baja)')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tipo de movimiento',
                'verbose_name_plural': 'Catálogo de tipos de movimientos',
            },
        ),
        migrations.CreateModel(
            name='LastVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filesType', models.CharField(choices=[('Entidades', 'Entidades'), ('Municipios', 'Municipios'), ('Localidades', 'Localidades')], max_length=15, verbose_name='Tipo de Catálogo')),
                ('filesVersion', models.DateField(verbose_name='Versión')),
                ('uploadedDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Último periodo cargado',
                'verbose_name_plural': 'Versiones vigentes',
            },
        ),
        migrations.CreateModel(
            name='FileMovements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cgo_act', models.CharField(max_length=2, verbose_name='Código de actualización')),
                ('descgo_act', models.CharField(max_length=110, verbose_name='Descripción del código de actualización')),
                ('mov_cant', models.IntegerField(verbose_name='Cantidad')),
                ('move_type', models.CharField(choices=[('Alta', 'Alta'), ('Baja', 'Baja'), ('Ambas', 'Ambas')], default='Ambas', max_length=5, verbose_name='Tipo de movimiento (Alta/Baja)')),
                ('UploadFiles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admincatalogos.UploadFiles')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
