# Generated by Django 3.0.4 on 2020-08-06 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admincatalogos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfiles',
            name='actLoad',
            field=models.FileField(upload_to='catalogos/1a273ea783510887c28433ebd0ae8ca9/', verbose_name='Registro de Actualización'),
        ),
        migrations.AlterField(
            model_name='uploadfiles',
            name='catLoad',
            field=models.FileField(upload_to='catalogos/1a273ea783510887c28433ebd0ae8ca9/', verbose_name='Catalogo'),
        ),
        migrations.AlterField(
            model_name='uploadfiles',
            name='eqvLoad',
            field=models.FileField(upload_to='catalogos/1a273ea783510887c28433ebd0ae8ca9/', verbose_name='Tabla de Equivalencias'),
        ),
        migrations.AlterField(
            model_name='uploadfiles',
            name='filesId',
            field=models.CharField(default='1a273ea783510887c28433ebd0ae8ca9', max_length=32),
        ),
    ]
