# Generated by Django 3.0.4 on 2020-08-13 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admincatalogos', '0002_auto_20200806_0449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadfiles',
            name='filesName',
        ),
        migrations.AlterField(
            model_name='uploadfiles',
            name='actLoad',
            field=models.FileField(upload_to='catalogos/0f8a55806ba8816ede080c7f04ac8767/', verbose_name='Registro de Actualización'),
        ),
        migrations.AlterField(
            model_name='uploadfiles',
            name='catLoad',
            field=models.FileField(upload_to='catalogos/0f8a55806ba8816ede080c7f04ac8767/', verbose_name='Catalogo'),
        ),
        migrations.AlterField(
            model_name='uploadfiles',
            name='eqvLoad',
            field=models.FileField(upload_to='catalogos/0f8a55806ba8816ede080c7f04ac8767/', verbose_name='Tabla de Equivalencias'),
        ),
        migrations.AlterField(
            model_name='uploadfiles',
            name='filesId',
            field=models.CharField(default='0f8a55806ba8816ede080c7f04ac8767', max_length=32),
        ),
        migrations.AlterField(
            model_name='uploadfiles',
            name='filesType',
            field=models.CharField(choices=[('entidades', 'entidades'), ('municipios', 'municipios'), ('localidades', 'localidades')], max_length=15, verbose_name='Tipo de Catálogo'),
        ),
    ]
