# Generated by Django 3.0.4 on 2020-08-13 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admincatalogos', '0003_auto_20200812_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfiles',
            name='actLoad',
            field=models.FileField(upload_to='catalogos/ab3f77c7f61a59752b71b7712f4404a9/', verbose_name='Registro de Actualización'),
        ),
        migrations.AlterField(
            model_name='uploadfiles',
            name='catLoad',
            field=models.FileField(upload_to='catalogos/ab3f77c7f61a59752b71b7712f4404a9/', verbose_name='Catalogo'),
        ),
        migrations.AlterField(
            model_name='uploadfiles',
            name='eqvLoad',
            field=models.FileField(upload_to='catalogos/ab3f77c7f61a59752b71b7712f4404a9/', verbose_name='Tabla de Equivalencias'),
        ),
        migrations.AlterField(
            model_name='uploadfiles',
            name='filesId',
            field=models.CharField(default='ab3f77c7f61a59752b71b7712f4404a9', max_length=32),
        ),
        migrations.AlterField(
            model_name='uploadfiles',
            name='processStep',
            field=models.CharField(default='-', max_length=80),
        ),
        migrations.AlterField(
            model_name='uploadfiles',
            name='status',
            field=models.CharField(default='Inicial', max_length=80),
        ),
        migrations.AlterField(
            model_name='uploadfiles',
            name='statusDesc',
            field=models.CharField(default='Carga inicial', max_length=254),
        ),
    ]
