# Generated by Django 3.0.4 on 2020-08-15 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admincatalogos', '0004_auto_20200813_0128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadfiles',
            name='task_id',
        ),
        migrations.RemoveField(
            model_name='uploadfilestrack',
            name='task_id',
        ),
        migrations.AddField(
            model_name='uploadfiles',
            name='activo',
            field=models.BooleanField(default=False, verbose_name='Proceso activo'),
        ),
        migrations.AddField(
            model_name='uploadfilestrack',
            name='activo',
            field=models.BooleanField(default=False, verbose_name='Proceso activo'),
        ),
        migrations.AlterField(
            model_name='uploadfiles',
            name='actLoad',
            field=models.FileField(upload_to='media/catalogos/1c5c820cdb426f1905bb88dbed4bf6c8/', verbose_name='Registro de Actualización'),
        ),
        migrations.AlterField(
            model_name='uploadfiles',
            name='catLoad',
            field=models.FileField(upload_to='media/catalogos/1c5c820cdb426f1905bb88dbed4bf6c8/', verbose_name='Catalogo'),
        ),
        migrations.AlterField(
            model_name='uploadfiles',
            name='eqvLoad',
            field=models.FileField(upload_to='media/catalogos/1c5c820cdb426f1905bb88dbed4bf6c8/', verbose_name='Tabla de Equivalencias'),
        ),
        migrations.AlterField(
            model_name='uploadfiles',
            name='filesId',
            field=models.CharField(default='1c5c820cdb426f1905bb88dbed4bf6c8', max_length=32),
        ),
    ]
