# Generated by Django 3.0.4 on 2020-08-18 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admincatalogos', '0005_auto_20200814_1929'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadfilestrack',
            options={'verbose_name': 'Tack completo', 'verbose_name_plural': 'Todos los tracks'},
        ),
        migrations.AlterField(
            model_name='uploadfiles',
            name='actLoad',
            field=models.FileField(upload_to='media/catalogos/8db9262eb4d85e2a199ae864b534d74b/', verbose_name='Registro de Actualización'),
        ),
        migrations.AlterField(
            model_name='uploadfiles',
            name='catLoad',
            field=models.FileField(upload_to='media/catalogos/8db9262eb4d85e2a199ae864b534d74b/', verbose_name='Catalogo'),
        ),
        migrations.AlterField(
            model_name='uploadfiles',
            name='eqvLoad',
            field=models.FileField(upload_to='media/catalogos/8db9262eb4d85e2a199ae864b534d74b/', verbose_name='Tabla de Equivalencias'),
        ),
        migrations.AlterField(
            model_name='uploadfiles',
            name='filesId',
            field=models.CharField(default='8db9262eb4d85e2a199ae864b534d74b', max_length=32),
        ),
    ]
