# Generated by Django 3.0.4 on 2020-08-29 07:29

import admincatalogos.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admincatalogos', '0006_auto_20200817_1955'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filemovements',
            options={'verbose_name': 'Movimiento', 'verbose_name_plural': 'Movimientos por carga'},
        ),
        migrations.AlterModelOptions(
            name='movtypes',
            options={'verbose_name': 'Tipo de movimiento', 'verbose_name_plural': 'Tipos de movimientos'},
        ),
        migrations.RemoveField(
            model_name='filemovements',
            name='author',
        ),
        migrations.AlterField(
            model_name='filemovements',
            name='move_type',
            field=models.CharField(choices=[('alta', 'alta'), ('baja', 'baja'), ('ambas', 'ambas')], default='ambas', max_length=5, verbose_name='Tipo de movimiento (Alta/Baja)'),
        ),
        migrations.AlterField(
            model_name='lastversion',
            name='filesType',
            field=models.CharField(choices=[('entidades', 'entidades'), ('municipios', 'municipios'), ('localidades', 'localidades')], max_length=15, verbose_name='Tipo de Catálogo'),
        ),
        migrations.AlterField(
            model_name='lastversion',
            name='uploadedDate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de carga'),
        ),
        migrations.AlterField(
            model_name='movtypes',
            name='filesType',
            field=models.CharField(choices=[('entidades', 'entidades'), ('municipios', 'municipios'), ('localidades', 'localidades')], max_length=15, verbose_name='Tipo de Catálogo'),
        ),
        migrations.AlterField(
            model_name='movtypes',
            name='move_type',
            field=models.CharField(choices=[('alta', 'alta'), ('baja', 'baja'), ('ambas', 'ambas')], default='ambas', max_length=5, verbose_name='Tipo de movimiento (Alta/Baja)'),
        ),
        migrations.AlterField(
            model_name='uploadfiles',
            name='actLoad',
            field=models.FileField(upload_to=admincatalogos.models.files_path, verbose_name='Registro de Actualización'),
        ),
        migrations.AlterField(
            model_name='uploadfiles',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='uploadfiles',
            name='catLoad',
            field=models.FileField(upload_to=admincatalogos.models.files_path, verbose_name='Catalogo'),
        ),
        migrations.AlterField(
            model_name='uploadfiles',
            name='eqvLoad',
            field=models.FileField(upload_to=admincatalogos.models.files_path, verbose_name='Tabla de Equivalencias'),
        ),
        migrations.AlterField(
            model_name='uploadfiles',
            name='filesId',
            field=models.CharField(default='', max_length=32, verbose_name='Id de carga'),
        ),
        migrations.AlterField(
            model_name='uploadfiles',
            name='status',
            field=models.CharField(default='Inicial', max_length=80, verbose_name='Estatus'),
        ),
        migrations.AlterField(
            model_name='uploadfiles',
            name='uploadedDate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de carga'),
        ),
    ]
