# Generated by Django 3.0.4 on 2020-09-01 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admincatalogos', '0007_auto_20200829_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfiles',
            name='filesId',
            field=models.CharField(default='', max_length=32, unique=True, verbose_name='Id de carga'),
        ),
    ]
