# Generated by Django 3.0.4 on 2020-09-01 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admincatalogos', '0008_auto_20200901_0246'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfiles',
            name='stepNumber',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
    ]
