# Generated by Django 3.0.4 on 2020-09-11 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admincatalogos', '0009_uploadfiles_stepnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfiles',
            name='stepNumber',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name='Número de paso'),
        ),
        migrations.AlterField(
            model_name='uploadfilestrack',
            name='endTime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Hora de fin'),
        ),
        migrations.AlterField(
            model_name='uploadfilestrack',
            name='processStep',
            field=models.CharField(max_length=80, verbose_name='Paso'),
        ),
        migrations.AlterField(
            model_name='uploadfilestrack',
            name='startTime',
            field=models.DateTimeField(verbose_name='Hora de inicio'),
        ),
        migrations.AlterField(
            model_name='uploadfilestrack',
            name='status',
            field=models.CharField(max_length=80, verbose_name='Estatus'),
        ),
        migrations.AlterField(
            model_name='uploadfilestrack',
            name='statusDesc',
            field=models.CharField(max_length=254, verbose_name='Descripción del estatus'),
        ),
        migrations.AlterField(
            model_name='uploadfilestrack',
            name='stepNumber',
            field=models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Número de paso'),
        ),
    ]
