# Generated by Django 3.0.4 on 2020-09-18 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admincatalogos', '0010_auto_20200910_2229'),
    ]

    operations = [
        migrations.CreateModel(
            name='VersionesLocalidades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.DateField(verbose_name='Versión')),
                ('fecha_carga', models.DateField(verbose_name='Fecha de la carga')),
                ('num_regs', models.IntegerField(verbose_name='Número de registros')),
            ],
            options={
                'verbose_name': 'Versión',
                'verbose_name_plural': 'Versiones cargadas',
            },
        ),
    ]
