# Generated by Django 3.0.4 on 2020-09-18 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admincatalogos', '0012_versioneslocalidades_vigente'),
    ]

    operations = [
        migrations.AddField(
            model_name='versioneslocalidades',
            name='tipo',
            field=models.CharField(choices=[('entidades', 'entidades'), ('municipios', 'municipios'), ('localidades', 'localidades')], default='localidades', max_length=15, verbose_name='Tipo de Catálogo'),
        ),
        migrations.AlterField(
            model_name='versioneslocalidades',
            name='vigente',
            field=models.BooleanField(verbose_name='Vigente'),
        ),
    ]
