# Generated by Django 3.0.4 on 2020-09-11 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admincatalogos', '0010_auto_20200910_2229'),
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cat_Ent',
            new_name='Cat_Entidades',
        ),
        migrations.RenameModel(
            old_name='Hist_Ent',
            new_name='Hist_Entidades',
        ),
        migrations.RenameModel(
            old_name='Tmp_Cat_Ent',
            new_name='Tmp_Cat_Entidades',
        ),
    ]
