# Generated by Django 3.0.4 on 2020-09-15 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_auto_20200910_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat_entidades',
            name='par_id',
            field=models.IntegerField(null=True, verbose_name='Id de fusión'),
        ),
    ]
